name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Master branch'ına yapılan push ile pipeline tetiklenir
  pull_request:
    branches:
      - master  # Master branch'ına yapılan PR'lar için de pipeline çalışacak

jobs:
  build:
    runs-on: ubuntu-latest  # Bu job Ubuntu üzerinde çalışacak

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install  # package.json master branch'ında olduğu için bu işlem doğru çalışacak

      - name: Run tests
        run: npm test  # Testleri çalıştır

      - name: Build Docker image
        run: docker build -t batub16/devops-case-app:latest .

      - name: Push Docker image
        run: docker push batub16/devops-case-app:latest

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
